apiVersion: apps/v1
kind: Deployment
metadata:
  name: dept-service
  labels:
    app: dept-service
spec:
  replicas: 3  # Number of pods to run
  selector:
    matchLabels:
      app: dept-service
  template:
    metadata:
      labels:
        app: dept-service
    spec:
      containers:
        - name: dept-cntr
          image: 290622/department-img:latest  # Replace with your image name
          ports:
            - containerPort: 8081  # Port your Spring Boot app listens on
---
apiVersion: v1
kind: Service
metadata:
  name: dept-cntr
spec:
  selector:
    app: dept-service
  ports:
    - protocol: TCP
      port: 8081  # Port exposed inside the Kubernetes cluster
      targetPort: 8081  # Port Spring Boot app listens on
  type: LoadBalancer